# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/
print_pipeline_id: &print_pipeline_id
  steps:
    - run:
        name: Reusable Command to print workflowid
        command: echo $CIRCLE_WORKFLOW_ID

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm run setup && npm run lint
      - save_cache:
          key: packages_cache
          paths: /src/node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: packages_cache
  analyse:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit
workflows:
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test
          
